from __future__ import annotations

# Generated at release build time from concrete default feature dispatch.
# The GUI reads only these labels; it does not execute tools while browsing menus.
OUTPUT_KEYS = {
    'gameplay.continuous-action.generator-miner': ['preset', 'implementation', 'safety'],
    'gameplay.continuous-action.hold-attack': ['preset', 'implementation', 'safety'],
    'gameplay.continuous-action.hold-use': ['preset', 'implementation', 'safety'],
    'gameplay.continuous-action.concrete-converter': ['preset', 'implementation', 'safety'],
    'gameplay.continuous-action.auto-walk': ['preset', 'implementation', 'safety'],
    'gameplay.continuous-action.custom-hold': ['preset', 'implementation', 'safety'],
    'gameplay.periodic-interaction.auto-attack': ['preset', 'implementation', 'safety'],
    'gameplay.periodic-interaction.afk-mob-grinder': ['preset', 'implementation', 'safety'],
    'gameplay.periodic-interaction.livestock-breeder': ['preset', 'implementation', 'safety'],
    'gameplay.periodic-interaction.custom-periodic-action': ['preset', 'implementation', 'safety'],
    'gameplay.fishing.auto-fishing': ['preset', 'implementation', 'safety'],
    'gameplay.travel.basic-travel': ['preset', 'implementation', 'safety'],
    'gameplay.travel.sprint-travel': ['preset', 'implementation', 'safety'],
    'gameplay.travel.sprint-jump-travel': ['preset', 'implementation', 'safety'],
    'gameplay.travel.swim-travel': ['preset', 'implementation', 'safety'],
    'gameplay.travel.boat-travel': ['preset', 'implementation', 'safety'],
    'gameplay.travel.horse-camel-travel': ['preset', 'implementation', 'safety'],
    'gameplay.travel.elytra-launch': ['preset', 'implementation', 'safety'],
    'gameplay.travel.elytra-cruise': ['preset', 'implementation', 'safety'],
    'gameplay.travel.riptide-travel': ['preset', 'implementation', 'safety'],
    'gameplay.travel.spear-dash-travel': ['preset', 'implementation', 'safety'],
    'gameplay.travel.coordinate-travel': ['preset', 'implementation', 'safety'],
    'gameplay.travel.waypoint-travel': ['preset', 'implementation', 'safety'],
    'gameplay.travel.nether-assisted-travel': ['preset', 'implementation', 'safety'],
    'gameplay.mining.tunnel-miner': ['preset', 'implementation', 'safety'],
    'gameplay.mining.branch-miner': ['preset', 'implementation', 'safety'],
    'gameplay.mining.stair-excavator': ['preset', 'implementation', 'safety'],
    'gameplay.mining.area-excavator': ['preset', 'implementation', 'safety'],
    'gameplay.mining.strip-mine-optimizer': ['branches', 'branch_depth', 'side_tunnel_blocks', 'spacing'],
    'gameplay.mining.beacon-mining-planner': ['pyramid', 'coverage_side'],
    'gameplay.mining.quarry-planner': ['wizard', 'macro', 'coordinate_validation', 'width', 'length', 'depth', 'layers', 'row_distance', 'rows_per_layer', 'area', 'volume', 'perimeter', 'surface_area'],
    'gameplay.farming.crop-farmer': ['preset', 'implementation', 'safety'],
    'gameplay.farming.coordinate-row-farmer': ['preset', 'implementation', 'safety'],
    'gameplay.farming.multi-row-farmer': ['preset', 'implementation', 'safety'],
    'gameplay.farming.bone-meal-farmer': ['preset', 'implementation', 'safety'],
    'gameplay.farming.stationary-grow-harvest': ['preset', 'implementation', 'safety'],
    'gameplay.farming.tree-farm-cycle': ['preset', 'implementation', 'safety'],
    'gameplay.farming.farm-station-controller': ['preset', 'implementation', 'safety'],
    'gameplay.equipment.mending-grinder': ['preset', 'implementation', 'safety'],
    'gameplay.equipment.crossbow-volley': ['preset', 'implementation', 'safety'],
    'gameplay.equipment.hotbar-workflow': ['preset', 'implementation', 'safety'],
    'gameplay.equipment.tool-rotation': ['preset', 'implementation', 'safety'],
    'gameplay.equipment.durability-guard': ['preset', 'implementation', 'safety'],
    'gameplay.equipment.resource-guard': ['preset', 'implementation', 'safety'],
    'gameplay.equipment.food-manager': ['preset', 'implementation', 'safety'],
    'gameplay.equipment.offhand-workflow': ['preset', 'implementation', 'safety'],
    'gameplay.construction.line': ['preset', 'implementation', 'safety'],
    'gameplay.construction.rectangle': ['preset', 'implementation', 'safety'],
    'gameplay.construction.filled-rectangle': ['preset', 'implementation', 'safety'],
    'gameplay.construction.grid': ['preset', 'implementation', 'safety'],
    'gameplay.construction.rows': ['preset', 'implementation', 'safety'],
    'gameplay.construction.alternating-pattern': ['preset', 'implementation', 'safety'],
    'gameplay.construction.perimeter': ['preset', 'implementation', 'safety'],
    'gameplay.construction.repeating-segment': ['preset', 'implementation', 'safety'],
    'gameplay.automation.action-sequencer': ['preset', 'implementation', 'safety'],
    'gameplay.automation.route-runner': ['preset', 'implementation', 'safety'],
    'gameplay.automation.macro-recorder': ['record_types', 'recording_class', 'templates'],
    'gameplay.automation.macro-template': ['templates'],
    'gameplay.automation.branch-mine-wizard': ['wizard', 'macro', 'coordinate_validation', 'spacing', 'depth', 'branches', 'torch_spacing', 'estimated_side_distance'],
    'gameplay.automation.quarry-wizard': ['wizard', 'macro', 'coordinate_validation', 'width', 'length', 'depth', 'layers', 'row_distance', 'rows_per_layer', 'area', 'volume', 'perimeter', 'surface_area'],
    'gameplay.automation.tree-farm-wizard': ['wizard', 'macro', 'sapling_slot', 'bonemeal_slot', 'tool_slot'],
    'gameplay.automation.crop-farm-wizard': ['wizard', 'macro', 'coordinate_validation', 'rows', 'row_length'],
    'gameplay.automation.nether-highway-wizard': ['wizard', 'coordinate_validation', 'start', 'destination', 'sister_start', 'sister_destination', 'overworld_distance', 'nether_distance', 'travel_seconds'],
    'navigation.position.capture-position': ['action', 'method', 'parser'],
    'navigation.position.copy-sister-coordinates': ['action', 'conversion'],
    'navigation.position.save-sister-waypoint': ['action', 'storage'],
    'navigation.position.current-position': ['action', 'source'],
    'navigation.position.continuous-capture': ['action', 'interval_seconds'],
    'navigation.position.distance-announcer': ['distance', 'announcement'],
    'navigation.position.bearing-lock': ['bearing', 'target'],
    'navigation.coordinates.distance': ['horizontal', 'distance_3d'],
    'navigation.coordinates.bearing': ['bearing', 'cardinal'],
    'navigation.coordinates.midpoint': ['midpoint'],
    'navigation.coordinates.delta-xyz': ['dx', 'dy', 'dz'],
    'navigation.coordinates.travel-time': ['seconds'],
    'navigation.coordinates.chunk': ['x_min', 'x_max', 'z_min', 'z_max', 'chunk'],
    'navigation.coordinates.region': ['chunk_x_min', 'chunk_x_max', 'chunk_z_min', 'chunk_z_max', 'block_x_min', 'block_x_max', 'block_z_min', 'block_z_max', 'region'],
    'navigation.coordinates.chunk-center': ['x_min', 'x_max', 'z_min', 'z_max', 'center', 'chunk'],
    'navigation.coordinates.chunk-border': ['x_min', 'x_max', 'z_min', 'z_max', 'nearest_lines', 'chunk'],
    'navigation.coordinates.chunk-corner': ['x_min', 'x_max', 'z_min', 'z_max', 'corners', 'chunk'],
    'navigation.coordinates.region-border': ['chunk_x_min', 'chunk_x_max', 'chunk_z_min', 'chunk_z_max', 'block_x_min', 'block_x_max', 'block_z_min', 'block_z_max', 'region'],
    'navigation.coordinates.axis-distance': ['x', 'y', 'z'],
    'navigation.coordinates.cardinal-snap': ['input_yaw', 'cardinal', 'snapped_yaw'],
    'navigation.coordinates.chunk-line-navigator': ['x_min', 'x_max', 'z_min', 'z_max', 'nearest_lines', 'chunk'],
    'navigation.coordinates.ow-nether-conversion': ['converted'],
    'navigation.coordinates.coordinate-offset': ['result'],
    'navigation.coordinates.coordinate-history': ['action', 'storage'],
    'navigation.waypoints.create-waypoint': ['action', 'storage', 'persistent'],
    'navigation.waypoints.rename-waypoint': ['action', 'storage', 'persistent'],
    'navigation.waypoints.delete-waypoint': ['action', 'storage', 'persistent'],
    'navigation.waypoints.nearest-waypoint': ['operation', 'route', 'distance'],
    'navigation.waypoints.sort-waypoints-by-distance': ['operation', 'route', 'distance'],
    'navigation.waypoints.waypoint-route': ['operation', 'route', 'distance'],
    'navigation.waypoints.waypoint-groups': ['action', 'operations'],
    'navigation.routes.multi-stop-route': ['route', 'distance'],
    'navigation.routes.breadcrumb-simplifier': ['input_points', 'output_points'],
    'navigation.routes.coordinate-route': ['operation', 'start', 'target', 'distance', 'horizontal', 'bearing'],
    'navigation.routes.resource-route': ['operation', 'start', 'target', 'distance', 'horizontal', 'bearing'],
    'navigation.routes.structure-tour': ['operation', 'start', 'target', 'distance', 'horizontal', 'bearing'],
    'navigation.routes.biome-expedition': ['operation', 'start', 'target', 'distance', 'horizontal', 'bearing'],
    'navigation.routes.breadcrumb-recorder': ['operation', 'start', 'target', 'distance', 'horizontal', 'bearing'],
    'navigation.routes.expedition-recorder': ['operation', 'start', 'target', 'distance', 'horizontal', 'bearing'],
    'navigation.routes.survey-mode': ['operation', 'start', 'target', 'distance', 'horizontal', 'bearing'],
    'navigation.routes.loop-detection': ['operation', 'epsilon', 'algorithm'],
    'navigation.portal-helpers.sister-portal': ['nether', 'y'],
    'navigation.portal-helpers.standard-link-calculator': ['ideal_nether', 'ranked'],
    'navigation.portal-helpers.portal-conflict-analysis': ['routing', 'links'],
    'navigation.portal-helpers.optimal-portal-placement': ['selected', 'distance', 'margin', 'meets_margin'],
    'navigation.portal-helpers.portal-network': ['portals', 'by_dimension', 'links', 'cycles'],
    'navigation.portal-helpers.highway-planner': ['overworld_distance', 'nether_distance', 'travel_seconds'],
    'navigation.portal-helpers.portal-separation': ['distance_between_exits', 'ideal', 'other'],
    'navigation.portal-helpers.portal-coverage': ['radius', 'diameter', 'area'],
    'navigation.portal-helpers.multi-portal-jump': ['overworld', 'nether', 'second_overworld', 'second_nether', 'nether_leg'],
    'seed-tools.world-seed-recovery.nether-bedrock-cracker': ['policy', 'source_available', 'executable', 'source_dir', 'automatic_acquisition'],
    'seed-tools.slime.nearest-slime-chunk': ['nearest'],
    'seed-tools.slime.slime-radius': ['chunks', 'count', 'radius'],
    'seed-tools.slime.adjacent-pair': ['minimum_size', 'matches', 'count'],
    'seed-tools.slime.2x2-cluster': ['minimum_size', 'matches', 'count'],
    'seed-tools.slime.triple-cluster': ['minimum_size', 'matches', 'count'],
    'seed-tools.slime.quad-cluster': ['minimum_size', 'matches', 'count'],
    'seed-tools.slime.largest-connected-cluster': ['largest', 'size'],
    'seed-tools.slime.slime-density': ['slime_chunks', 'total_chunks', 'density'],
    'seed-tools.slime.farm-location-ranking': ['ranked'],
    'seed-tools.cubiomes.cubiomes-status': ['source_available', 'library', 'source_dir'],
    'seed-tools.cubiomes.cubiomes-biome-query': ['biome_id', 'seed', 'x', 'y', 'z', 'dimension', 'mc_enum', 'bundled_newest_enum'],
    'seed-tools.nether.asymmetric-portal-router': ['portals', 'by_dimension', 'links', 'cycles'],
    'seed-tools.nether.vertical-isolation-analyzer': ['vertical_pairs'],
    'seed-tools.nether.reliability-margin': ['margins'],
    'seed-tools.nether.bidirectional-link-matrix': ['links'],
    'seed-tools.nether.portal-graph': ['portals', 'by_dimension', 'links', 'cycles'],
    'seed-tools.nether.loop-detector': ['cycles'],
    'seed-tools.nether.travel-compression': ['overworld_gain', 'physical', 'conventional', 'gain_per_walk', 'reduction_vs_nether'],
    'seed-tools.nether.nether-biome-finder': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.nether.fortress-finder': ['operation', 'results'],
    'seed-tools.nether.bastion-finder': ['operation', 'results'],
    'seed-tools.nether.fortress-bastion-finder': ['operation', 'results'],
    'seed-tools.nether.nether-structure-density': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.nether.bedrock-pattern-helper': ['operation', 'policy', 'allowed'],
    'seed-tools.nether.asymmetric-jump-designer': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.nether.maximum-displacement': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.nether.repeating-network-generator': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.nether.destination-gate-planner': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.nether.portal-state-simulator': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.nether.routing-table-generator': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.nether.corridor-transport': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.nether.standard-route-comparison': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.nether.multi-destination-optimizer': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.nether.portal-reliability-heatmap': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.nether.portal-radius-visualizer': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.nether.portal-cost-optimizer': ['operation', 'origin', 'radius', 'nether_scale', 'seed'],
    'seed-tools.structures.structure-finder': ['seed', 'candidate_sets'],
    'seed-tools.structures.village': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.stronghold': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'backend_error', 'note'],
    'seed-tools.structures.trial-chamber': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.ancient-city': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.woodland-mansion': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.ocean-monument': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.desert-pyramid': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.jungle-temple': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.swamp-hut': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.igloo': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.pillager-outpost': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.ruined-portal': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.shipwreck': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.ocean-ruin': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.buried-treasure': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.mineshaft': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'backend_error', 'note'],
    'seed-tools.structures.nether-fortress': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.bastion': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.end-city': ['structure', 'candidate_chunks', 'count', 'region_size', 'chunk_range', 'salt', 'backend', 'mc_enum', 'note'],
    'seed-tools.structures.compound-search': ['operation', 'seed', 'radius', 'candidate_counts', 'total_candidates'],
    'seed-tools.structures.structure-chains': ['operation', 'seed', 'radius', 'candidate_counts', 'total_candidates'],
    'seed-tools.structures.isolated-structure-finder': ['operation', 'seed', 'radius', 'candidate_counts', 'total_candidates'],
    'seed-tools.structures.structure-cluster-finder': ['operation', 'seed', 'radius', 'candidate_counts', 'total_candidates'],
    'seed-tools.structures.structure-density': ['operation', 'seed', 'radius', 'candidate_counts', 'total_candidates'],
    'seed-tools.structures.structure-heatmap': ['operation', 'seed', 'radius', 'candidate_counts', 'total_candidates'],
    'seed-tools.structures.structure-corridor': ['operation', 'seed', 'radius', 'candidate_counts', 'total_candidates'],
    'seed-tools.structures.multi-target-locator': ['operation', 'seed', 'radius', 'candidate_counts', 'total_candidates'],
    'seed-tools.structures.portal-optimized-structure-search': ['operation', 'seed', 'radius', 'candidate_counts', 'total_candidates'],
    'seed-tools.spawners.dungeon-pig-spawner-locator': ['operation', 'mode', 'world_path', 'ready', 'note'],
    'seed-tools.spawners.double-spawner-locator': ['operation', 'mode', 'world_path', 'ready', 'note'],
    'seed-tools.spawners.triple-spawner-locator': ['operation', 'mode', 'world_path', 'ready', 'note'],
    'seed-tools.spawners.quad-spawner-locator': ['operation', 'mode', 'world_path', 'ready', 'note'],
    'seed-tools.spawners.spawner-cluster-ranking': ['operation', 'mode', 'world_path', 'ready', 'note'],
    'seed-tools.spawners.stronghold-silverfish': ['operation', 'mode', 'world_path', 'ready', 'note'],
    'seed-tools.spawners.trial-chamber-spawners': ['operation', 'mode', 'world_path', 'ready', 'note'],
    'seed-tools.biomes.current-biome': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.nearest-biome': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.rare-biome-search': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.largest-biome': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.largest-ocean': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.largest-mountain-chain': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.largest-cave-region': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.flat-terrain-finder': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.valley-finder': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.mountain-peak-finder': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.terrain-base-finder': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.island-finder': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.peninsula-detector': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.river-crossing-finder': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.lake-density': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.cliff-locator': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.biome-boundary': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.two-way-biome-intersection': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.three-way-biome-intersection': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.four-way-biome-intersection': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.biome-diversity-finder': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.biomes.largest-continuous-region': ['operation', 'samples', 'biome_counts', 'nearest_samples'],
    'seed-tools.local-area.32-chunk-analysis': ['operation', 'center_chunk', 'radius_chunks', 'slime_chunks', 'sampled_chunks'],
    'seed-tools.local-area.biome-composition': ['operation', 'center_chunk', 'radius_chunks', 'slime_chunks', 'sampled_chunks'],
    'seed-tools.local-area.structure-counts': ['operation', 'center_chunk', 'radius_chunks', 'slime_chunks', 'sampled_chunks'],
    'seed-tools.local-area.slime-distribution': ['operation', 'center_chunk', 'radius_chunks', 'slime_chunks', 'sampled_chunks'],
    'seed-tools.local-area.notable-locations': ['operation', 'center_chunk', 'radius_chunks', 'slime_chunks', 'sampled_chunks'],
    'seed-tools.local-area.technical-score': ['operation', 'center_chunk', 'radius_chunks', 'slime_chunks', 'sampled_chunks'],
    'seed-tools.local-area.build-score': ['operation', 'center_chunk', 'radius_chunks', 'slime_chunks', 'sampled_chunks'],
    'seed-tools.local-area.exploration-score': ['operation', 'center_chunk', 'radius_chunks', 'slime_chunks', 'sampled_chunks'],
    'seed-tools.world-analysis.spawn-analysis': ['operation', 'seed', 'center_chunk', 'radius', 'structure_candidate_counts', 'sampled_chunks'],
    'seed-tools.world-analysis.technical-world-score': ['operation', 'seed', 'center_chunk', 'radius', 'structure_candidate_counts', 'sampled_chunks'],
    'seed-tools.world-analysis.resource-score': ['operation', 'seed', 'center_chunk', 'radius', 'structure_candidate_counts', 'sampled_chunks'],
    'seed-tools.world-analysis.seed-comparison': ['operation', 'seed', 'center_chunk', 'radius', 'structure_candidate_counts', 'sampled_chunks'],
    'seed-tools.world-analysis.ore-distribution': ['operation', 'seed', 'center_chunk', 'radius', 'structure_candidate_counts', 'sampled_chunks'],
    'seed-tools.world-analysis.ore-exposure-estimate': ['operation', 'seed', 'center_chunk', 'radius', 'structure_candidate_counts', 'sampled_chunks'],
    'seed-tools.world-analysis.ancient-city-area-analysis': ['operation', 'seed', 'center_chunk', 'radius', 'structure_candidate_counts', 'sampled_chunks'],
    'seed-tools.world-analysis.cave-exposure-estimate': ['operation', 'seed', 'center_chunk', 'radius', 'structure_candidate_counts', 'sampled_chunks'],
    'seed-tools.world-analysis.chunk-loading-simulator': ['operation', 'seed', 'center_chunk', 'radius', 'structure_candidate_counts', 'sampled_chunks'],
    'seed-tools.world-analysis.spawn-chunk-optimizer': ['operation', 'seed', 'center_chunk', 'radius', 'structure_candidate_counts', 'sampled_chunks'],
    'seed-tools.world-analysis.search-radius-optimizer': ['operation', 'seed', 'center_chunk', 'radius', 'structure_candidate_counts', 'sampled_chunks'],
    'calculators.coordinate.distance-calculator': ['distance_3d', 'horizontal'],
    'calculators.coordinate.bearing-calculator': ['bearing'],
    'calculators.coordinate.midpoint-calculator': ['midpoint'],
    'calculators.coordinate.travel-time-calculator': ['seconds'],
    'calculators.coordinate.nether-conversion-calculator': ['converted'],
    'calculators.coordinate.coordinate-snap': ['block', 'chunk_center'],
    'calculators.coordinate.delta-xyz-calculator': ['dx', 'dy', 'dz'],
    'calculators.build.area': ['area', 'volume', 'perimeter', 'surface_area'],
    'calculators.build.volume': ['volume', 'area', 'perimeter', 'surface_area'],
    'calculators.build.surface-area': ['surface_area', 'area', 'volume', 'perimeter'],
    'calculators.build.perimeter': ['perimeter', 'area', 'volume', 'surface_area'],
    'calculators.build.block-count': ['block_count', 'area', 'volume', 'perimeter', 'surface_area'],
    'calculators.build.stacks': ['items', 'stacks', 'remainder', 'shulkers', 'double_chests'],
    'calculators.build.shulkers': ['items', 'stacks', 'remainder', 'shulkers', 'double_chests'],
    'calculators.build.double-chests': ['items', 'stacks', 'remainder', 'shulkers', 'double_chests'],
    'calculators.build.foundation-planner': ['foundation_planner', 'area', 'volume', 'perimeter', 'surface_area'],
    'calculators.build.stair-calculator': ['rise', 'run', 'blocks'],
    'calculators.build.spiral-staircase-planner': ['diameter', 'height', 'steps_per_turn', 'clockwise', 'points', 'blocks'],
    'calculators.build.catenary-calculator': ['span', 'sag', 'height_delta', 'points', 'blocks'],
    'calculators.build.roof-pitch': ['rise', 'run', 'pitch', 'layers'],
    'calculators.build.wall-segments': ['perimeter', 'segments'],
    'calculators.build.bridge-span': ['span', 'supports', 'spacing'],
    'calculators.build.grid': ['points'],
    'calculators.build.lighting-grid': ['count', 'positions'],
    'calculators.build.pillar-spacing': ['x_supports', 'z_supports'],
    'calculators.build.road-planner': ['length', 'width', 'blocks', 'markers'],
    'calculators.build.crop-layout': ['plots', 'area', 'spacing'],
    'calculators.build.gradient-ratio': ['rise', 'run', 'ratio', 'percent_grade'],
    'calculators.build.chunk-grid-builder': ['chunks_x', 'chunks_z', 'chunks'],
    'calculators.build.circle-layer-export': ['radius', 'points'],
    'calculators.build.beacon-offset': ['center_offset', 'pyramid'],
    'calculators.shapes.circle': ['points', 'count'],
    'calculators.shapes.filled-circle': ['points', 'count'],
    'calculators.shapes.sphere': ['points', 'count'],
    'calculators.shapes.hollow-sphere': ['points', 'count'],
    'calculators.shapes.dome': ['points', 'count'],
    'calculators.shapes.cylinder': ['points', 'count'],
    'calculators.shapes.cone': ['points', 'count'],
    'calculators.shapes.spiral': ['points', 'count'],
    'calculators.shapes.helix': ['points', 'count'],
    'calculators.shapes.double-helix': ['strand_a', 'strand_b', 'count'],
    'calculators.shapes.hexagon': ['vertices', 'count'],
    'calculators.shapes.octagon': ['vertices', 'count'],
    'calculators.shapes.ellipse': ['points', 'count'],
    'calculators.shapes.pyramid': ['layers', 'count'],
    'calculators.shapes.diamond': ['points', 'count'],
    'calculators.shapes.rounded-rectangle': ['width', 'length', 'corner_radius', 'straight_section', 'count'],
    'calculators.shapes.arch': ['points', 'count'],
    'calculators.redstone.tick-converter': ['ticks', 'seconds', 'minutes', 'hours'],
    'calculators.redstone.hopper-timer': ['ticks', 'seconds', 'minutes', 'hours'],
    'calculators.redstone.comparator-strength': ['signal'],
    'calculators.redstone.repeater-delay': ['redstone_ticks', 'ticks', 'seconds', 'minutes', 'hours'],
    'calculators.redstone.observer-delay': ['redstone_ticks', 'ticks', 'seconds', 'minutes', 'hours'],
    'calculators.redstone.minecart-timing': ['distance', 'speed_blocks_per_second', 'seconds', 'ticks'],
    'calculators.redstone.water-stream-timing': ['distance', 'assumed_speed', 'seconds', 'note'],
    'calculators.redstone.ice-boat-timing': ['distance', 'speed', 'seconds'],
    'calculators.redstone.crafter-throughput': ['items_per_hour'],
    'calculators.redstone.pulse-extender': ['redstone_ticks', 'ticks', 'seconds', 'minutes', 'hours'],
    'calculators.redstone.clock-period': ['redstone_ticks', 'ticks', 'seconds', 'minutes', 'hours'],
    'calculators.redstone.counter-timing': ['redstone_ticks', 'ticks', 'seconds', 'minutes', 'hours'],
    'calculators.redstone.signal-timing': ['redstone_ticks', 'ticks', 'seconds', 'minutes', 'hours'],
    'calculators.storage.storage-capacity': ['items', 'stacks', 'remainder', 'shulkers', 'double_chests'],
    'calculators.storage.bulk-materials': ['items', 'stacks', 'remainder', 'shulkers', 'double_chests'],
    'calculators.storage.item-compression': ['input', 'compressed', 'remainder'],
    'calculators.storage.material-logistics': ['items', 'capacity_per_trip', 'trips'],
    'calculators.storage.transport-trips': ['capacity_per_trip', 'trips'],
    'calculators.storage.shulker-requirement': ['items', 'stacks', 'remainder', 'shulkers', 'double_chests'],
    'calculators.storage.chest-requirement': ['items', 'stacks', 'remainder', 'shulkers', 'double_chests'],
    'calculators.storage.material-weight': ['blocks', 'stacks', 'shulkers'],
    'calculators.farm.crop-yield': ['plants', 'harvests', 'expected_items', 'note'],
    'calculators.farm.tree-yield': ['trees', 'cycles', 'logs_at_4_per_tree'],
    'calculators.farm.animal-breeding': ['starting_adults', 'cycles', 'population_upper_bound'],
    'calculators.farm.villager-breeding': ['breedings', 'bread', 'carrots'],
    'calculators.farm.furnace-array': ['furnaces', 'items'],
    'calculators.farm.fuel-optimizer': ['items_to_smelt', 'coal_like_fuel', 'bamboo_like_fuel'],
    'calculators.farm.beacon-pyramid': ['levels', 'layers', 'single_beacon_blocks', 'blocks', 'beacons'],
    'calculators.farm.beacon-coverage': ['levels', 'layers', 'single_beacon_blocks', 'blocks', 'beacons'],
    'calculators.farm.sugar-cane-layout': ['plants', 'spacing', 'linear_length'],
    'calculators.farm.bamboo-layout': ['plants', 'spacing', 'linear_length'],
    'calculators.farm.kelp-tower': ['columns', 'height', 'plant_blocks'],
    'calculators.farm.bee-apiary': ['hives', 'recommended_flowers', 'spacing'],
    'calculators.farm.villager-hall-layout': ['villagers', 'workstations', 'beds_if_breeding', 'aisle_spacing'],
    'calculators.farm.animal-pen': ['animals', 'suggested_area', 'suggested_side'],
    'calculators.farm.crop-row-calculator': ['plants', 'spacing', 'linear_length'],
    'calculators.farm.slime-farm-optimizer': ['operation', 'center', 'radius', 'recommended_buffer', 'area'],
    'calculators.farm.fortress-farm-planner': ['operation', 'center', 'radius', 'recommended_buffer', 'area'],
    'calculators.farm.trial-chamber-planner': ['operation', 'center', 'radius', 'recommended_buffer', 'area'],
    'calculators.technical.mob-cap-calculator': ['players', 'eligible_chunks', 'category_base_cap', 'local_scaled_cap', 'simple_independent_player_upper_bound'],
    'calculators.technical.despawn-radius-planner': ['player', 'soft_despawn_radius', 'hard_despawn_radius', 'hard_despawn_diameter', 'hard_square_bounds'],
    'calculators.technical.item-sorter-planner': ['modules', 'filter_items_reserved', 'hopper_slots', 'distinct_sorted_items'],
    'calculators.technical.chunk-alignment': ['x_min', 'x_max', 'z_min', 'z_max'],
    'calculators.technical.region-alignment': ['chunk_x_min', 'chunk_x_max', 'chunk_z_min', 'chunk_z_max', 'block_x_min', 'block_x_max', 'block_z_min', 'block_z_max'],
    'calculators.technical.cardinal-alignment': ['x_axis_distance', 'z_axis_distance', 'nearest_axis'],
    'calculators.technical.build-rotation': ['90', '180', '270'],
    'calculators.technical.symmetry': ['mirror_x', 'mirror_z'],
    'calculators.technical.blueprint-coordinates': ['origin', 'chunk', 'region'],
    'calculators.technical.chunk-loader-planner': ['loaders', 'x_count', 'z_count', 'spacing_chunks'],
    'calculators.technical.loaded-chunk-area': ['chunks', 'side_chunks', 'side_blocks'],
    'calculators.technical.simulation-distance': ['radius_chunks', 'side_chunks', 'chunks', 'side_blocks', 'area_blocks'],
    'calculators.technical.render-distance': ['chunks', 'side_chunks', 'side_blocks'],
    'calculators.technical.spawn-sphere': ['radius', 'diameter', 'volume'],
    'calculators.technical.mob-spawn-area': ['inner_radius', 'outer_radius', 'shell_volume'],
    'calculators.technical.random-tick-area': ['chunks', 'side_chunks', 'side_blocks'],
    'calculators.technical.spawnproof-calculator': ['radius', 'square_blocks', 'circle_area'],
    'calculators.technical.farm-separation': ['distance'],
    'calculators.technical.iron-farm-spacing': ['distance'],
    'calculators.technical.villager-gossip-radius': ['distance'],
    'calculators.technical.raid-distance': ['distance'],
    'calculators.technical.perimeter-planner': ['blocks', 'seconds', 'minutes', 'hours', 'items', 'stacks', 'stack_remainder', 'shulkers', 'double_chests'],
    'calculators.technical.branch-density-calculator': ['branches', 'branch_depth', 'side_tunnel_blocks', 'spacing'],
    'calculators.technical.tunnel-progress': ['blocks', 'speed', 'seconds'],
    'calculators.technical.torch-planner': ['distance', 'spacing', 'torches'],
    'calculators.technical.chunk-loader-radius': ['loaders', 'x_count', 'z_count', 'spacing_chunks'],
    'calculators.technical.mob-cap': ['base_hostile_cap', 'eligible_chunks', 'scaled_cap'],
    'calculators.technical.guardian-area': ['monument_center', 'recommended_spawnproof_radius', 'square_side'],
    'calculators.technical.fortress-bounding-box': ['center', 'nominal_piece_scan_radius', 'note'],
    'calculators.technical.mob-switch-radius': ['recommended_distance', 'diameter'],
    'calculators.speedrunning.eye-throw-triangulation': ['target'],
    'calculators.speedrunning.stronghold-ring': ['rings'],
    'calculators.speedrunning.blind-travel': ['target_nether', 'distance'],
    'calculators.speedrunning.blaze-route-planner': ['operation', 'center', 'radius', 'recommended_buffer', 'area'],
    'calculators.resource-usage.xp-level-calculator': ['start', 'end', 'xp', 'start_total', 'end_total'],
    'calculators.resource-usage.mending-repair-calculator': ['xp', 'eligible_items', 'maximum_total_durability_repaired', 'average_if_evenly_distributed'],
    'calculators.resource-usage.anvil-prior-work-planner': ['operations', 'prior_work_penalties', 'total_prior_work_penalty', 'recommendation'],
    'calculators.resource-usage.tool-wear': ['actions', 'expected_durability_used', 'conservative_durability_used'],
    'calculators.resource-usage.food-usage': ['rate_per_hour', 'hours', 'total', 'resource'],
    'calculators.resource-usage.rocket-usage': ['rate_per_hour', 'hours', 'total', 'resource'],
    'calculators.resource-usage.fuel-usage': ['rate_per_hour', 'hours', 'total', 'resource'],
    'calculators.resource-usage.torch-usage': ['rate_per_hour', 'hours', 'total', 'resource'],
    'calculators.resource-usage.bone-meal-usage': ['rate_per_hour', 'hours', 'total', 'resource'],
    'calculators.resource-usage.material-progress': ['actions', 'expected_durability_used', 'conservative_durability_used'],
    'calculators.resource-usage.resource-goal-calculator': ['rate_per_hour', 'hours', 'total', 'resource'],
    'calculators.end.gateway-calculator': ['gateway_ring_radius_approx', 'angle_deg', 'x', 'z'],
    'calculators.end.outer-island-distance': ['distance', 'gateway_ring_reference'],
    'calculators.end.end-city-route': ['start', 'target', 'distance'],
    'rng-tools.rng-recovery.enchantment-rng-seed-cracker': ['version', 'cached', 'launcher', 'sha256_expected', 'java_detected', 'upstream_support', 'world_seed'],
    'rng-tools.rng-recovery.java-lcg-state-recovery-2-nextint': ['candidate_count', 'candidates', 'source', 'world_seed_recovery'],
    'rng-tools.rng-recovery.java-lcg-state-recovery-nextlong': ['candidate_count', 'candidates', 'source', 'world_seed_recovery'],
    'rng-tools.rng-recovery.java-lcg-state-inspector': ['input_internal_state', 'steps_applied', 'state_after_steps', 'next_int_predictions', 'state_after_predictions', 'world_seed_recovery'],
    'rng-tools.enchanting.enchantment-probability': ['single_chance', 'attempts', 'at_least_one', 'percent'],
    'rng-tools.enchanting.bookshelf-planner': ['bookshelves', 'max_table_level', 'full_power'],
    'rng-tools.enchanting.lapis-cost-calculator': ['enchantments', 'lapis', 'xp_levels_spent'],
    'rng-tools.enchanting.grindstone-reset-planner': ['rerolls', 'dummy_enchants', 'minimum_lapis'],
    'rng-tools.enchanting.enchantment-sequence-simulator': ['seed', 'sequence'],
    'rng-tools.enchanting.enchanting-simulator': ['operation', 'seed', 'rolls', 'at_least_one'],
    'rng-tools.enchanting.best-enchantment-search': ['operation', 'seed', 'rolls', 'at_least_one'],
    'rng-tools.enchanting.xp-level-planner': ['operation', 'seed', 'rolls', 'at_least_one'],
    'rng-tools.enchanting.enchantment-table-layout': ['operation', 'seed', 'rolls', 'at_least_one'],
    'rng-tools.drops.mob-drop-simulator': ['expected_drops', 'single_chance', 'attempts', 'at_least_one', 'percent'],
    'rng-tools.probability.rng-sequence-viewer': ['seed', 'sequence'],
    'rng-tools.probability.rng-timeline': ['seed', 'sequence'],
    'rng-tools.probability.rng-probability-calculator': ['single_chance', 'attempts', 'at_least_one', 'percent'],
    'rng-tools.probability.loot-odds-calculator': ['single_chance', 'attempts', 'at_least_one', 'percent'],
    'rng-tools.probability.rare-drop-odds': ['single_chance', 'attempts', 'at_least_one', 'percent'],
    'rng-tools.probability.barter-odds': ['single_chance', 'attempts', 'at_least_one', 'percent'],
    'rng-tools.probability.trial-reward-odds': ['single_chance', 'attempts', 'at_least_one', 'percent'],
    'rng-tools.probability.enchantment-odds': ['operation', 'seed', 'rolls', 'at_least_one'],
    'rng-tools.loot.loot-table-simulator': ['operation', 'seed', 'attempts', 'success_indices', 'successes', 'empirical_rate', 'expected_rate'],
    'rng-tools.loot.structure-loot-simulator': ['operation', 'seed', 'attempts', 'success_indices', 'successes', 'empirical_rate', 'expected_rate'],
    'rng-tools.loot.trial-chamber-loot-simulator': ['operation', 'seed', 'attempts', 'success_indices', 'successes', 'empirical_rate', 'expected_rate'],
    'rng-tools.loot.fishing-loot-simulator': ['operation', 'seed', 'attempts', 'success_indices', 'successes', 'empirical_rate', 'expected_rate'],
    'rng-tools.loot.archaeology-loot-simulator': ['operation', 'seed', 'attempts', 'success_indices', 'successes', 'empirical_rate', 'expected_rate'],
    'rng-tools.loot.piglin-barter-simulator': ['operation', 'seed', 'attempts', 'success_indices', 'successes', 'empirical_rate', 'expected_rate'],
    'rng-tools.loot.trial-spawner-reward-simulator': ['operation', 'seed', 'attempts', 'success_indices', 'successes', 'empirical_rate', 'expected_rate'],
    'rng-tools.generation-rng.decoration-rng': ['operation', 'rng_seed', 'sample_positions'],
    'rng-tools.generation-rng.feature-placement-rng': ['operation', 'rng_seed', 'sample_positions'],
    'rng-tools.generation-rng.ore-placement-simulator': ['operation', 'rng_seed', 'sample_positions'],
    'rng-tools.generation-rng.tree-generation-simulator': ['operation', 'rng_seed', 'sample_positions'],
    'rng-tools.generation-rng.geode-generator': ['operation', 'rng_seed', 'sample_positions'],
    'rng-tools.generation-rng.trial-chamber-generation': ['operation', 'rng_seed', 'sample_positions'],
    'rng-tools.generation-rng.structure-placement-preview': ['operation', 'rng_seed', 'sample_positions'],
    'villager-explorer.trades.trade-browser': ['operation', 'trades_loaded', 'preview', 'source_version'],
    'villager-explorer.trades.trade-search': ['operation', 'trades_loaded', 'preview', 'source_version'],
    'villager-explorer.trades.trade-comparison': ['operation', 'trades_loaded', 'preview', 'source_version'],
    'villager-explorer.trades.emerald-calculator': ['operation', 'trades_loaded', 'preview', 'source_version'],
    'villager-explorer.trades.trade-cycle-calculator': ['operation', 'trades_loaded', 'preview', 'source_version'],
    'villager-explorer.trades.librarian-browser': ['operation', 'trades_loaded', 'preview', 'source_version'],
    'villager-explorer.trades.refresh-trades-from-installed-version': ['operation', 'trades_loaded', 'preview', 'source_version'],
    'villager-explorer.professions.armorer': ['profession', 'trades', 'source_version'],
    'villager-explorer.professions.butcher': ['profession', 'trades', 'source_version'],
    'villager-explorer.professions.cartographer': ['profession', 'trades', 'source_version'],
    'villager-explorer.professions.cleric': ['profession', 'trades', 'source_version'],
    'villager-explorer.professions.farmer': ['profession', 'trades', 'source_version'],
    'villager-explorer.professions.fisherman': ['profession', 'trades', 'source_version'],
    'villager-explorer.professions.fletcher': ['profession', 'trades', 'source_version'],
    'villager-explorer.professions.leatherworker': ['profession', 'trades', 'source_version'],
    'villager-explorer.professions.librarian': ['profession', 'trades', 'source_version'],
    'villager-explorer.professions.mason': ['profession', 'trades', 'source_version'],
    'villager-explorer.professions.shepherd': ['profession', 'trades', 'source_version'],
    'villager-explorer.professions.toolsmith': ['profession', 'trades', 'source_version'],
    'villager-explorer.professions.weaponsmith': ['profession', 'trades', 'source_version'],
    'villager-explorer.helpers.zombie-cure-calculator': ['base_cost', 'discount', 'result', 'minimum'],
    'villager-explorer.helpers.villager-hall-calculator': ['wizard', 'villagers', 'workstations', 'minimum_length'],
    'villager-explorer.helpers.workstation-count': ['villagers', 'workstations'],
    'villager-explorer.helpers.breeding-food-calculator': ['breedings', 'bread', 'carrots', 'potatoes', 'beetroot'],
    'wizards.mining.branch-mine-setup': ['wizard', 'macro', 'coordinate_validation', 'spacing', 'depth', 'branches', 'torch_spacing', 'estimated_side_distance'],
    'wizards.mining.quarry-setup': ['wizard', 'macro', 'coordinate_validation', 'width', 'length', 'depth', 'layers', 'row_distance', 'rows_per_layer', 'area', 'volume', 'perimeter', 'surface_area'],
    'wizards.mining.perimeter-setup': ['wizard', 'macro', 'coordinate_validation', 'width', 'length', 'depth', 'blocks', 'items', 'stacks', 'stack_remainder', 'shulkers', 'double_chests'],
    'wizards.farming.crop-farm-setup': ['wizard', 'macro', 'coordinate_validation', 'rows', 'row_length'],
    'wizards.farming.tree-farm-setup': ['wizard', 'macro', 'sapling_slot', 'bonemeal_slot', 'tool_slot'],
    'wizards.farming.villager-hall-setup': ['wizard', 'villagers', 'workstations', 'minimum_length'],
    'wizards.portals.nether-highway-setup': ['wizard', 'coordinate_validation', 'start', 'destination', 'sister_start', 'sister_destination', 'overworld_distance', 'nether_distance', 'travel_seconds'],
    'wizards.portals.portal-network-setup': ['wizard', 'portals', 'validation'],
    'wizards.portals.asymmetric-portal-setup': ['wizard', 'stages', 'validation'],
    'wizards.building.build-material-setup': ['wizard', 'area', 'volume', 'perimeter', 'surface_area', 'items', 'stacks', 'stack_remainder', 'shulkers', 'double_chests'],
    'wizards.building.lighting-grid-setup': ['wizard', 'count', 'positions'],
    'wizards.building.beacon-network-setup': ['wizard', 'levels', 'layers', 'single_beacon_blocks', 'blocks', 'beacons'],
    'utilities.version-backend.minecraft-version': ['selected_version', 'editable'],
    'utilities.version-backend.compatibility-report': ['minecraft', 'cubiomes_source', 'cubiomes_library', 'bedrock_cracker', 'world_seed_policy'],
    'utilities.version-backend.installed-version-scan': ['versions', 'searched'],
    'utilities.version-backend.trade-data-status': ['source', 'trade_count'],
    'utilities.version-backend.cubiomes-setup-and-status': ['source_available', 'library'],
    'utilities.version-backend.nether-bedrock-cracker-status': ['available', 'automatic_acquisition', 'source_dir', 'executable'],
    'utilities.profiles.export-profiles': ['action', 'format', 'settings_object'],
    'utilities.profiles.import-profiles': ['action', 'format', 'settings_object'],
    'utilities.controls.control-bindings': ['action', 'persistent'],
    'utilities.controls.turn-calibration': ['action', 'degrees', 'mouse_units'],
    'utilities.controls.movement-calibration': ['action', 'distance', 'seconds'],
    'utilities.controls.coordinate-capture-settings': ['action', 'source'],
    'utilities.controls.backup-settings': ['action', 'format', 'path'],
    'safety.controls.emergency-stop': ['method', 'behavior'],
    'safety.controls.pause-resume': ['method', 'behavior'],
    'safety.controls.release-held-inputs': ['method', 'behavior'],
    'safety.controls.focus-loss-stop': ['method', 'behavior'],
    'safety.controls.restore-hotbar': ['control', 'restore_slot'],
    'safety.controls.runtime-limit': ['control', 'max_seconds'],
    'safety.controls.delayed-start': ['control', 'delay_seconds'],
    'safety.controls.action-counter': ['control', 'counter_limit'],
    'safety.controls.stuck-detection': ['control', 'window_seconds', 'minimum_displacement'],
    'safety.controls.recovery-attempts': ['control', 'max_attempts'],
}
